export const pokemonGroupTypes = [
  {
    id: "physical",
    label: "Physical",
    types: ["normal", "fighting", "flying"],
  },
  {
    id: "elemental",
    label: "Elemental",
    types: ["fire", "water", "grass", "electric", "ice", "bug"],
  },
  {
    id: "earthMetal",
    label: "Earth / Metal",
    types: ["ground", "rock", "steel"],
  },
  {
    id: "special",
    label: "Special",
    types: ["psychic", "ghost", "dark", "dragon", "fairy", "posion"],
  },
];

export const statusFilterOptions = [
  {
    id: "all",
    label: "All",
    value: "all",
  },
  {
    id: "seen",
    label: "Seen",
    value: "seen",
  },
  {
    id: "caught",
    label: "Caught",
    value: "caught",
  },
];

export const mockPokemon = [
  {
    id: "# 001",
    name: "Bulbasaur",
    types: ["Grass", "Poison"],
    sprite: "/images/pokemon/bulbasaur.png",
    isFavorite: false,
    caught: true,
    seen: true,
    stats: {
      hp: 45,
      attack: 49,
      defense: 49,
      specialAttack: 65,
      specialDefense: 65,
      speed: 45,
    },
    flavorText:
      "A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokémon.",
  },
  {
    id: "# 004",
    name: "Charmander",
    types: ["Fire"],
    sprite: "/images/pokemon/charmander.png",
    isFavorite: true,
    caught: true,
    seen: true,
    stats: {
      hp: 39,
      attack: 52,
      defense: 43,
      specialAttack: 60,
      specialDefense: 50,
      speed: 65,
    },
    flavorText:
      "Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail.",
  },
  {
    id: "# 007",
    name: "Squirtle",
    types: ["Water"],
    sprite: "/images/pokemon/squirtle.png",
    isFavorite: false,
    caught: false,
    seen: true,
    stats: {
      hp: 44,
      attack: 48,
      defense: 65,
      specialAttack: 50,
      specialDefense: 64,
      speed: 43,
    },
    flavorText:
      "After birth, its back swells and hardens into a shell. It powerfully sprays foam from its mouth.",
  },
  {
    id: "# 010",
    name: "Caterpie",
    types: ["Bug"],
    sprite: "/images/pokemon/caterpie.png",
    isFavorite: false,
    caught: true,
    seen: true,
    stats: {
      hp: 45,
      attack: 30,
      defense: 35,
      specialAttack: 20,
      specialDefense: 20,
      speed: 45,
    },
    flavorText:
      "Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls.",
  },
  {
    id: "# 012",
    name: "Butterfree",
    types: ["Bug", "Flying"],
    sprite: "/images/pokemon/butterfree.png",
    isFavorite: false,
    caught: false,
    seen: true,
    stats: {
      hp: 60,
      attack: 45,
      defense: 50,
      specialAttack: 90,
      specialDefense: 80,
      speed: 70,
    },
    flavorText:
      "In battle, it flaps its wings at high speed to release highly toxic dust into the air.",
  },
  {
    id: "# 016",
    name: "Pidgey",
    types: ["Normal", "Flying"],
    sprite: "/images/pokemon/pidgey.png",
    isFavorite: false,
    caught: true,
    seen: true,
    stats: {
      hp: 40,
      attack: 45,
      defense: 40,
      specialAttack: 35,
      specialDefense: 35,
      speed: 56,
    },
    flavorText:
      "A common sight in forests and woods. It flaps its wings at ground level to kick up sand.",
  },
  {
    id: "# 019",
    name: "Rattata",
    types: ["Normal"],
    sprite: "/images/pokemon/rattata.png",
    isFavorite: false,
    caught: false,
    seen: true,
    stats: {
      hp: 30,
      attack: 56,
      defense: 35,
      specialAttack: 25,
      specialDefense: 35,
      speed: 72,
    },
    flavorText:
      "Bites anything when it attacks. Small and very quick, it is a common sight in many places.",
  },
  {
    id: "# 025",
    name: "Pikachu",
    types: ["Electric"],
    sprite: "/images/pokemon/pikachu.png",
    isFavorite: true,
    caught: true,
    seen: true,
    stats: {
      hp: 35,
      attack: 55,
      defense: 40,
      specialAttack: 50,
      specialDefense: 50,
      speed: 90,
    },
    flavorText:
      "When several of these Pokémon gather, their electricity could build and cause lightning storms.",
  },
  {
    id: "# 027",
    name: "Sandshrew",
    types: ["Ground"],
    sprite: "/images/pokemon/sandshrew.png",
    isFavorite: false,
    caught: false,
    seen: true,
    stats: {
      hp: 50,
      attack: 75,
      defense: 85,
      specialAttack: 20,
      specialDefense: 30,
      speed: 40,
    },
    flavorText:
      "Its body is dry. When it gets cold at night, its skin becomes wrinkled.",
  },
  {
    id: "# 037",
    name: "Vulpix",
    types: ["Fire"],
    sprite: "/images/pokemon/vulpix.png",
    isFavorite: true,
    caught: false,
    seen: true,
    stats: {
      hp: 38,
      attack: 41,
      defense: 40,
      specialAttack: 50,
      specialDefense: 65,
      speed: 65,
    },
    flavorText:
      "At the time of birth, it has just one tail. Its tail splits from the tip as it grows older.",
  },
  {
    id: "# 039",
    name: "Jigglypuff",
    types: ["Normal", "Fairy"],
    sprite: "/images/pokemon/jigglypuff.png",
    isFavorite: false,
    caught: true,
    seen: true,
    stats: {
      hp: 115,
      attack: 45,
      defense: 20,
      specialAttack: 45,
      specialDefense: 25,
      speed: 20,
    },
    flavorText:
      "Uses its cute round eyes to enrapture opponents. It then sings a soothing melody to lull foes to sleep.",
  },
  {
    id: "# 050",
    name: "Diglett",
    types: ["Ground"],
    sprite: "/images/pokemon/diglett.png",
    isFavorite: false,
    caught: false,
    seen: true,
    stats: {
      hp: 10,
      attack: 55,
      defense: 25,
      specialAttack: 35,
      specialDefense: 45,
      speed: 95,
    },
    flavorText:
      "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.",
  },
  {
    id: "# 052",
    name: "Meowth",
    types: ["Normal"],
    sprite: "/images/pokemon/meowth.png",
    isFavorite: false,
    caught: false,
    seen: true,
    stats: {
      hp: 40,
      attack: 45,
      defense: 35,
      specialAttack: 40,
      specialDefense: 40,
      speed: 90,
    },
    flavorText:
      "Adores circular objects. Wanders the streets on a nightly basis to look for dropped loose change.",
  },
  {
    id: "# 054",
    name: "Psyduck",
    types: ["Water"],
    sprite: "/images/pokemon/psyduck.png",
    isFavorite: false,
    caught: false,
    seen: true,
    stats: {
      hp: 50,
      attack: 52,
      defense: 48,
      specialAttack: 65,
      specialDefense: 50,
      speed: 55,
    },
    flavorText:
      "While lulling its enemies with its vacant look, this wily Pokémon will use psychokinetic powers.",
  },
  {
    id: "# 063",
    name: "Abra",
    types: ["Psychic"],
    sprite: "/images/pokemon/abra.png",
    isFavorite: false,
    caught: true,
    seen: true,
    stats: {
      hp: 25,
      attack: 20,
      defense: 15,
      specialAttack: 105,
      specialDefense: 55,
      speed: 90,
    },
    flavorText:
      "Sleeps 18 hours a day. If it senses danger, it teleports itself to safety even as it sleeps.",
  },
];
