export const POKE_BASE_URL = "https://pokeapi.co/api/v2/";

export const pokemonGroupTypes = [
  {
    id: "physical",
    label: "Physical",
    types: ["normal", "fighting", "flying"],
  },
  {
    id: "elemental",
    label: "Elemental",
    types: ["fire", "water", "grass", "electric", "ice", "bug"],
  },
  {
    id: "earthMetal",
    label: "Earth / Metal",
    types: ["ground", "rock", "steel"],
  },
  {
    id: "special",
    label: "Special",
    types: ["psychic", "ghost", "dark", "dragon", "fairy", "poison"],
  },
];

export const statusFilterOptions = [
  {
    id: "all",
    label: "All",
    value: "all",
  },
  {
    id: "seen",
    label: "Seen",
    value: "seen",
  },
  {
    id: "caught",
    label: "Caught",
    value: "caught",
  },
];

export const CACHE_KEYS = {
  POKE_LIST: "poke:list:kanto151",
  POKEDEX_INDEX: "poke:index:kanto151",
  TYPE_LIST: "type:list",
  TYPE_INDEX: "type:index",
};

const pokemonModel = {
  sprites: [],

  attributes: {
    height: "",
    weight: "",
    color: "",
    habitat: "",
  },

  flavorText: [],

  moves: [],

  evolutionChain: {
    type: "linear" || "non-linear",
    chain: {
      one: {
        name: "",
        id: "",
        growthRate: "",
        trigger: "",
        additionalInfo: {
          expRequired: "",
          lvlRequired: "",
        },
      },
    },
  },
};

export const mockPokemon = [
  {
    id: 1,
    name: "Bulbasaur",
    types: ["grass", "poison"],
    sprite: "src/images/pokemonSprites/1.png",
    isFavorite: false,
    description: "A strange seed was planted on its back at birth.",
    stats: { hp: 45, attack: 49, defense: 49, speed: 45 },
    abilities: ["Overgrow", "Chlorophyll"],
  },
  {
    id: 2,
    name: "Ivysaur",
    types: ["grass", "poison"],
    sprite: "src/images/pokemonSprites/2.png",
    isFavorite: false,
    description:
      "When its bulb grows large, it appears to lose the ability to stand.",
    stats: { hp: 60, attack: 62, defense: 63, speed: 60 },
    abilities: ["Overgrow", "Chlorophyll"],
  },
  {
    id: 3,
    name: "Venusaur",
    types: ["grass", "poison"],
    sprite: "src/images/pokemonSprites/3.png",
    isFavorite: false,
    description: "The plant blooms when it is absorbing solar energy.",
    stats: { hp: 80, attack: 82, defense: 83, speed: 80 },
    abilities: ["Overgrow", "Chlorophyll"],
  },
  {
    id: 4,
    name: "Charmander",
    types: ["fire"],
    sprite: "src/images/pokemonSprites/4.png",
    isFavorite: false,
    description: "Obviously prefers hot places.",
    stats: { hp: 39, attack: 52, defense: 43, speed: 65 },
    abilities: ["Blaze", "Solar Power"],
  },
  {
    id: 5,
    name: "Charmeleon",
    types: ["fire"],
    sprite: "src/images/pokemonSprites/5.png",
    isFavorite: false,
    description: "When it swings its burning tail, it raises the temperature.",
    stats: { hp: 58, attack: 64, defense: 58, speed: 80 },
    abilities: ["Blaze", "Solar Power"],
  },
  {
    id: 6,
    name: "Charizard",
    types: ["fire", "flying"],
    sprite: "src/images/pokemonSprites/6.png",
    isFavorite: false,
    description: "Spits fire that is hot enough to melt boulders.",
    stats: { hp: 78, attack: 84, defense: 78, speed: 100 },
    abilities: ["Blaze", "Solar Power"],
  },
  {
    id: 7,
    name: "Squirtle",
    types: ["water"],
    sprite: "src/images/pokemonSprites/7.png",
    isFavorite: false,
    description: "Shoots water at prey while in the water.",
    stats: { hp: 44, attack: 48, defense: 65, speed: 43 },
    abilities: ["Torrent", "Rain Dish"],
  },
  {
    id: 8,
    name: "Wartortle",
    types: ["water"],
    sprite: "src/images/pokemonSprites/8.png",
    isFavorite: false,
    description: "It is said to live 10,000 years.",
    stats: { hp: 59, attack: 63, defense: 80, speed: 58 },
    abilities: ["Torrent", "Rain Dish"],
  },
  {
    id: 9,
    name: "Blastoise",
    types: ["water"],
    sprite: "src/images/pokemonSprites/9.png",
    isFavorite: false,
    description: "A brutal Pokémon with pressurized water jets.",
    stats: { hp: 79, attack: 83, defense: 100, speed: 78 },
    abilities: ["Torrent", "Rain Dish"],
  },
  {
    id: 10,
    name: "Caterpie",
    types: ["bug"],
    sprite: "src/images/pokemonSprites/10.png",
    isFavorite: false,
    description: "Its short feet are tipped with suction pads.",
    stats: { hp: 45, attack: 30, defense: 35, speed: 45 },
    abilities: ["Shield Dust", "Run Away"],
  },
  {
    id: 11,
    name: "Metapod",
    types: ["bug"],
    sprite: "src/images/pokemonSprites/11.png",
    isFavorite: false,
    description: "Hardens its shell to protect from attacks.",
    stats: { hp: 50, attack: 20, defense: 55, speed: 30 },
    abilities: ["Shed Skin"],
  },
  {
    id: 12,
    name: "Butterfree",
    types: ["bug", "flying"],
    sprite: "src/images/pokemonSprites/12.png",
    isFavorite: false,
    description: "Uses its wings to scatter toxic dust.",
    stats: { hp: 60, attack: 45, defense: 50, speed: 70 },
    abilities: ["Compound Eyes", "Tinted Lens"],
  },
  {
    id: 13,
    name: "Weedle",
    types: ["bug", "poison"],
    sprite: "src/images/pokemonSprites/13.png",
    isFavorite: false,
    description: "Often found in forests, eating leaves.",
    stats: { hp: 40, attack: 35, defense: 30, speed: 50 },
    abilities: ["Shield Dust", "Run Away"],
  },
  {
    id: 14,
    name: "Kakuna",
    types: ["bug", "poison"],
    sprite: "src/images/pokemonSprites/14.png",
    isFavorite: false,
    description: "Able to move only slightly. Hardens its shell.",
    stats: { hp: 45, attack: 25, defense: 50, speed: 35 },
    abilities: ["Shed Skin"],
  },
  {
    id: 15,
    name: "Beedrill",
    types: ["bug", "poison"],
    sprite: "src/images/pokemonSprites/15.png",
    isFavorite: false,
    description:
      "Flies at high speed and attacks using its large venomous stingers.",
    stats: { hp: 65, attack: 90, defense: 40, speed: 75 },
    abilities: ["Swarm", "Sniper"],
  },
];

export const mockTeams = [
  {
    id: "team-001",
    name: "Kanto Starters Core",
    description:
      "Solid early-game squad built around starter lines and utility.",
    lastUpdated: "2025-12-13T10:12:00Z",
    isFavorite: true,
    players: [1, 4, 7, 25, 39, 52],
  },
  {
    id: "team-002",
    name: "Gym Runner",
    description: "Fast coverage picks for sweeping early gyms.",
    lastUpdated: "2025-12-10T18:30:00Z",
    isFavorite: false,
    players: [16, 18, 27, 58, 63, 74],
  },
  {
    id: "team-003",
    name: "Rock & Ground Breakers",
    description: "Built to handle Electric, Fire, and normal threats.",
    lastUpdated: "2025-12-09T21:05:00Z",
    isFavorite: false,
    players: [50, 51, 66, 95, 111, 112],
  },
  {
    id: "team-004",
    name: "Water Control",
    description: "Water-heavy team with status and bulk.",
    lastUpdated: "2025-12-08T14:44:00Z",
    isFavorite: true,
    players: [54, 55, 60, 61, 72, 73],
  },
  {
    id: "team-005",
    name: "Psychic Pressure",
    description: "High special power and control tools.",
    lastUpdated: "2025-12-06T16:10:00Z",
    isFavorite: false,
    players: [64, 65, 96, 97, 122, 124],
  },
  {
    id: "team-006",
    name: "Poison & Sleep",
    description: "Status-heavy team focused on poison/sleep setups.",
    lastUpdated: "2025-12-05T09:20:00Z",
    isFavorite: false,
    players: [23, 24, 43, 44, 69, 70],
  },
  {
    id: "team-007",
    name: "Electric & Speed",
    description: "Speedy picks and electric coverage for momentum.",
    lastUpdated: "2025-12-04T19:55:00Z",
    isFavorite: true,
    players: [26, 81, 82, 100, 101, 125],
  },
  {
    id: "team-008",
    name: "Late-Game Heavy Hitters",
    description: "High power options for endgame battles.",
    lastUpdated: "2025-12-03T12:01:00Z",
    isFavorite: false,
    players: [130, 131, 134, 143, 149, 150],
  },
  {
    id: "team-009",
    name: "Flying Utility",
    description: "Map mobility and flexible matchups.",
    lastUpdated: "2025-12-02T08:40:00Z",
    isFavorite: false,
    players: [21, 22, 83, 84, 85, 142],
  },
  {
    id: "team-010",
    name: "Fire & Ice Coverage",
    description: "Balanced offense with strong coverage options.",
    lastUpdated: "2025-12-01T23:18:00Z",
    isFavorite: true,
    players: [37, 38, 59, 126, 135, 146],
  },
];

export const pikachu = {
  id: 25,
  formattedId: "#025",
  name: "Pikachu",

  types: ["electric"],

  stats: {
    hp: 35,
    attack: 55,
    defense: 40,
    specialAttack: 50,
    specialDefense: 50,
    speed: 90,
  },

  attributes: {
    height: 4,
    weight: 60,
    color: "Yellow",
    habitat: "Forest",
  },

  eggGroups: ["ground", "fairy"],

  flavorText: [
    "When several of these POKéMON gather, their electricity could build and cause lightning storms.",
    "It keeps its tail raised to monitor its surroundings. If you yank its tail, it will try to bite you.",
    "This intelligent POKéMON roasts hard BERRIES with electricity to make them tender enough to eat.",
    "It raises its tail to check its surroundings. The tail is sometimes struck by lightning in this pose.",
  ],

  moves: {
    levelUp: [
      {
        level: 1,
        name: "Thunder Shock",
        type: "electric",
        category: "special",
        power: 40,
        accuracy: 100,
        pp: 30,
        effect: "May paralyze the target.",
      },
      {
        level: 1,
        name: "Growl",
        type: "normal",
        category: "status",
        power: null,
        accuracy: 100,
        pp: 40,
        effect: "Lowers the target’s Attack by 1 stage.",
      },
      {
        level: 4,
        name: "Tail Whip",
        type: "normal",
        category: "status",
        power: null,
        accuracy: 100,
        pp: 30,
        effect: "Lowers the target’s Defense by 1 stage.",
      },
      {
        level: 8,
        name: "Quick Attack",
        type: "normal",
        category: "physical",
        power: 40,
        accuracy: 100,
        pp: 30,
        effect: "Usually goes first.",
      },
      {
        level: 12,
        name: "Double Team",
        type: "normal",
        category: "status",
        power: null,
        accuracy: null,
        pp: 15,
        effect: "Raises user’s evasion.",
      },
      {
        level: 16,
        name: "Thunder Wave",
        type: "electric",
        category: "status",
        power: null,
        accuracy: 90,
        pp: 20,
        effect: "Paralyzes the target.",
      },
      {
        level: 20,
        name: "Electro Ball",
        type: "electric",
        category: "special",
        power: null,
        accuracy: 100,
        pp: 10,
        effect: "Power increases with user’s Speed advantage.",
      },
      {
        level: 24,
        name: "Spark",
        type: "electric",
        category: "physical",
        power: 65,
        accuracy: 100,
        pp: 20,
        effect: "May paralyze the target.",
      },
      {
        level: 28,
        name: "Slam",
        type: "normal",
        category: "physical",
        power: 80,
        accuracy: 75,
        pp: 20,
        effect: null,
      },
      {
        level: 34,
        name: "Discharge",
        type: "electric",
        category: "special",
        power: 80,
        accuracy: 100,
        pp: 15,
        effect: "May paralyze all nearby Pokémon.",
      },
      {
        level: 40,
        name: "Thunderbolt",
        type: "electric",
        category: "special",
        power: 90,
        accuracy: 100,
        pp: 15,
        effect: "May paralyze the target.",
      },
    ],

    tm: [
      {
        tm: "TM01",
        name: "Mega Punch",
        type: "normal",
        category: "physical",
        power: 80,
        accuracy: 85,
        pp: 20,
        effect: null,
      },
      {
        tm: "TM05",
        name: "Thunder Punch",
        type: "electric",
        category: "physical",
        power: 75,
        accuracy: 100,
        pp: 15,
        effect: "May paralyze the target.",
      },
      {
        tm: "TM10",
        name: "Thunder Wave",
        type: "electric",
        category: "status",
        power: null,
        accuracy: 90,
        pp: 20,
        effect: "Paralyzes the target.",
      },
      {
        tm: "TM24",
        name: "Thunderbolt",
        type: "electric",
        category: "special",
        power: 90,
        accuracy: 100,
        pp: 15,
        effect: "May paralyze the target.",
      },
    ],
  },
};

export const pikachuSprites = [
  {
    id: 0,
    spriteName: "front_default",
    url: "src/images/pokemonSprites/pikachu/front_default.png",
  },
  {
    id: 1,
    spriteName: "back_default",
    url: "src/images/pokemonSprites/pikachu/back_default.png",
  },
  {
    id: 2,
    spriteName: "front_female",
    url: "src/images/pokemonSprites/pikachu/front_female.png",
  },
  {
    id: 3,
    spriteName: "back_female",
    url: "src/images/pokemonSprites/pikachu/back_female.png",
  },
  {
    id: 4,
    spriteName: "front_shiny",
    url: "src/images/pokemonSprites/pikachu/front_shiny.png",
  },
  {
    id: 5,
    spriteName: "back_shiny",
    url: "src/images/pokemonSprites/pikachu/back_shiny.png",
  },
  {
    id: 6,
    spriteName: "front_shiny_female",
    url: "src/images/pokemonSprites/pikachu/front_shiny_female.png",
  },
  {
    id: 7,
    spriteName: "back_shiny_female",
    url: "src/images/pokemonSprites/pikachu/back_shiny_female.png",
  },
];

export const raichu = {
  id: 26,
  formattedId: "#026",
  name: "Raichu",
  types: ["Electric"],

  stats: {
    hp: 60,
    attack: 90,
    defense: 55,
    specialAttack: 90,
    specialDefense: 80,
    speed: 110,
  },

  moves: {
    levelUp: [
      {
        level: 1,
        name: "Thunder Shock",
        type: "Electric",
        category: "Special",
        power: 40,
        accuracy: 100,
        pp: 30,
      },
      {
        level: 1,
        name: "Quick Attack",
        type: "Normal",
        category: "Physical",
        power: 40,
        accuracy: 100,
        pp: 30,
      },
      {
        level: 1,
        name: "Tail Whip",
        type: "Normal",
        category: "Status",
        power: null,
        accuracy: 100,
        pp: 30,
      },
      {
        level: 1,
        name: "Thunderbolt",
        type: "Electric",
        category: "Special",
        power: 90,
        accuracy: 100,
        pp: 15,
      },
    ],
    tm: [
      {
        tm: "TM24",
        name: "Thunderbolt",
        type: "Electric",
        category: "Special",
        power: 90,
        accuracy: 100,
        pp: 15,
      },
      {
        tm: "TM25",
        name: "Thunder",
        type: "Electric",
        category: "Special",
        power: 110,
        accuracy: 70,
        pp: 10,
      },
      {
        tm: "TM34",
        name: "Shock Wave",
        type: "Electric",
        category: "Special",
        power: 60,
        accuracy: null,
        pp: 20,
      },
      {
        tm: "TM10",
        name: "Hidden Power",
        type: "Normal",
        category: "Special",
        power: "*",
        accuracy: 100,
        pp: 15,
      },
    ],
  },
};
